import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {montserrat} from "@/app/font";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} "bg-white h-full w-full"`}>
            {children}
      </body>
    </html>
  );
}
